/*
====================================================
04_intermediate_queries.sql
Project: DataShop
Description: Intermediate business analysis using JOINs,
aggregations and grouping.

Focus:
- Revenue analysis
- Customer behavior
- Product performance
====================================================
*/

-- -------------------------------------------------
-- Revenue by product
-- Calculates total revenue generated by each product
-- -------------------------------------------------
SELECT
    p.product_name,
    SUM(oi.quantity) AS total_quantity_sold,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM products p 
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY total_revenue DESC;

-- -------------------------------------------------
-- Revenue by customer
-- Identifies customers who generate the most revenue
-- -------------------------------------------------
SELECT
    c.full_name,
    COUNT(o.order_id) AS total_order,
    SUM(o.total_amount) AS total_spent
FROM customers c 
JOIN orders o
	ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.full_name
ORDER BY total_spent DESC;

-- -------------------------------------------------
-- Top 5 best-sellling products (by revenue)
-- -------------------------------------------------
SELECT 
    p.product_name,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM products p
JOIN order_items oi
	ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_revenue DESC
LIMIT 5;

-- -------------------------------------------------
-- Revenue by product category
-- -------------------------------------------------
SELECT
	p.category,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM products p
JOIN order_items oi
	ON p.product_id = oi.product_id
GROUP BY p.category
ORDER BY total_revenue DESC;

-- -------------------------------------------------
-- Monthly revenue analysis
-- -------------------------------------------------
SELECT
	DATE_FORMAT(order_date, '%Y-%m') AS year_months,
    SUM(total_amount) AS monthly_revenue
FROM orders
GROUP BY year_months
ORDER BY year_months;